#!/opt/local/bin/bash

# bashrc TEMPLATE
# 2018-11-03T13:00



##########
### EMACS
##########

## EMACS SERVERS
# Start the terminal server daemon=termserver
# Use termserver --kill to, you know, kill it
# -------------------------------------------------------------------------------
termserver --start
alias ect='emacsclient -qs termserver'

## EMACS ALIASES
alias edprofile='sudo  emacs -Q /private/etc/profile'
alias ed.profile='sudo emacs -Q ~/.profile'
alias ed.bash_profile='sudo emacs -Q ~/.bash_profile'
alias edbashrc='sudo   emacs -Q /private/etc/bashrc'
alias ed.bashrc='sudo  emacs -Q ~/.bashrc'
alias edtmuxconf='sudo emacs -Q /private/etc/tmux.conf'




open -jb org.gnu.Emacs --args --eval '(server-start nil)'
emacsclient -s server --eval '(progn (server-force-delete) (save-buffers-kill-terminal))'

echo ===============================================================================
echo \'ecg FILE \&\' runs \'emacsclient FILE \&\' using the EmacsMac server \'server\'
echo \'ect FILE\' runs \'emacsclient FILE\' using the terminal emacs server \'termserver\'
echo ===============================================================================

ecg() {
  emacsclient -cqs server "$@" &
}

initEmacs() {
  emacsclient -s server ${EMACS_HOME}/${EMACS_INIT}
}

### EDIT CONFIG FILES
alias edprofile='sudo emacs /private/etc/profile'
alias edbashrc='sudo emacs /private/etc/bashrc'
alias edtmuxconf='sudo emacs /private/etc/tmux.conf'

### LIST
alias ls='ls -GF'
alias lsl='ls -lh'
alias lsd='lsl | grep ^d | sed -Ee s/^.*\(\[\ \]\)\(\[^\ \]*\)$/\\2/'
